### ISSUE TITLE
Не открываются Другие сезоны

### ISSUE THREAD

**Issue by ArStudio** [dein0s/seasonvar_ru.bundle#1]
Список сезонов отображается, когда нажимаешь на Другие сезоны, но сами серии не загружаются

**Comment by dein0s** [comment]
1) не отображается папка "озвучки" или не воспроизводятся сами серии?
2) это происходит со всеми сериалами или с каким-то конкретным?
3) указывали свой api ключ в настройках канала?
4) прикрепите, пожалуйста, логи плагина сразу после выполнения описанной вами последовательности действий
